const USER_ACTIONS = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REDUCE_ITEM: 'REDUCE_ITEM',
    GOOGLE_SIGN_IN_START : 'GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS : 'GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAILURE : 'GOOGLE_SIGN_IN_FAILURE',
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS : 'EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAILURE : 'EMAIL_SIGN_IN_FAILURE'

};
export default USER_ACTIONS;