const USER_ACTIONS = {
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REDUCE_ITEM: 'REDUCE_ITEM'
};
export default USER_ACTIONS;